### ISSUE TITLE
Handle 429 status codes (too many requests)

### ISSUE THREAD

**Issue by chapinb** [chapinb/chickadee#10]
Requirements:
* Catch 429 error codes, delay until the next minute and try again with the same dataset.
* Put this logic in a while loop.
* Log a message to the end-user to let them know what's happening.
* Create a unit test with a data set of 18k distinct IP addresses

**Comment by chapinb** [comment]
This is specifically for ip-api.com requests. Will need to handle differently per backend.

**Comment by vladc** [comment]
> The returned HTTP header X-Rl contains the number of requests remaining in the current rate limit window. X-Ttl contains the seconds until the limit is reset.
Your implementation should always check the value of the X-Rl header, and if its is 0 you MUST NOT send any more requests for the duration of X-Ttl in seconds.

As per the [new documentation](https://ip-api.com/docs/api:json), the code should be restructured:
- remove the defined limits 
- always verify the X-Rl header,
- sleep/delay for time based on X-Ttl

**Comment by chapinb** [comment]
Thank you @vladc! Looks like I missed that documentation, that is a much-preferred approach (and easier to implement). It'll also improve performance for infrequent tool runs with < 1500 IPs (which is the most common use case).

**Comment by chapinb** [comment]
Corrected and completed in a3b5cb413f35c381eb8c37cc63c886c9a648557d
