### ISSUE TITLE
Function Name Printed on Execution

### ISSUE THREAD

**Issue by ethanf0725** [chapinb/chickadee#9]
When running the script, the function name is printed out and is slightly confusing, as in the following example:

> 2019-10-10 17:15:00,075 chickadee.py INFO chickadee entry 219 Starting Chickadee
2019-10-10 17:15:06,721 chickadee.py INFO chickadee entry 226 Chickadee complete

Would also like to see output here for "X number of lines parsed, ### being processed after deduplication"

**Comment by chapinb** [comment]
Completed in eaf3d883e45fafbbd2ee531620a828a92d9f7196
